# Automatically deploy the latest changes to the FTP server.
on:
  # Triggers the workflow on push events to the specified branch.
  push:
    branches: [ "demo/UA92" ]

  # Allows this workflow to be run manually from the Actions tab.
  workflow_dispatch:

name: 🚀 Auto-Deploy
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    env:
      VRCA_DEFAULT_DOMAIN_URL: ${{ secrets.ua92verse_default_domain }}
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - uses: actions/setup-node@master

    - name: 📥 Install project dependencies
      run: npm install

    - name: ⚒️ Build the project
      run: npm run build

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ftp.vircadia.com
        username: ${{ secrets.ua92verse_ftp_username }}
        password: ${{ secrets.ua92verse_ftp_password }}
        local-dir: dist/spa/
        server-dir: ${{ secrets.ua92verse_ftp_dir }}
        dry-run: false
